### ISSUE TITLE
Waiting for agents to reach version 1

### ISSUE THREAD

**Issue by FlaxHaxx** [mongodb/mongodb-kubernetes-operator#1394]
I installed the Community Kubernetes Operator in a namespace called `mongodb` using the [kubectl installation method](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md#install-in-a-different-namespace-using-kubectl).

When I then deployed the Replica Set using the below yaml the pods keep restarting and the operator health check fails.

```yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-dev
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.1"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: queue-api
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-queue-api-password
      roles:
        - name: dbAdmin
          db: queue-api-dev
        - name: readWrite
          db: queue-api-dev
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-queue-api-password
  namespace: mongodb
spec:
  encryptedData:
    password: AgAM2A2TB7L3jExTN2mL+UiafgX5oFxab/4WhNOFLV0Kp/ZZJ7EGhYAbNhxAPugAV+VyokS2xSex5kItmUcmuxGZ4aJRED/fdMqpeTgYVFQZkaOdlE0uYRKscP7cBGjRHEFzRVjb6PNVez39j0ByJsYD1cQPK5jXaRC0wPDo10QoQxzcsK/gyBByKtxm/DPyJ5mB1Hsf2NAo83Pzy08K3N2cnvZxi/FKZMXtQgbg3c+ddGc6kr+KbHwfxmLGyssOMZieC5aDsyqFZCHLuEHjqvWZJm82ofTIxbjIKd9InPJfhy7zSxG7yIkIZBdsDDHwzREn9NewBJ8vq8aROcWuNgGSGUaqKbwWXLuJb0ToS7zpVzNdDVRSd2HUCM1H7Y8hfFKbhzA88atvFZJ9GcG4JidSQO7C8KhkpehCw59db5Dq2twMb0FMx58p24xG5WOWr5fcVjVTpBxYkog25Ep2m1JjfcyXhXWWx5RkL1lOvUitl4xWxvpSAlFClYRXCQr89ClQt5mpbFRdE8w/F/y7Z1GXcG+bGlgbdeZlnvxpbAXM3vfZKyt0KrEpoooEs78hR2z6V1f6M7tg7QIjdaL9t1HzzCw2M7Wie8BIIDyP9hGynRIiLhPluc1SN1LeT1G0bg+rjDQsBKOk7RZSXrmvVpITbJaVei2ool7S0d3oS4QsYmzs+cXOGfnwrDLXNliSsnQjX2EwEq81kmX7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongodb-queue-api-password
      namespace: mongodb
```
This is the output from `kubectl -n mongodb get all`.

```sh
NAME                                               READY   STATUS             RESTARTS          AGE
pod/mongodb-dev-0                                  0/2     CrashLoopBackOff   173 (4m57s ago)   14h
pod/mongodb-kubernetes-operator-74965cfd5d-5s74j   1/1     Running            0                 14h

NAME                      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
service/mongodb-dev-svc   ClusterIP   None         <none>        27017/TCP   14h

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mongodb-kubernetes-operator   1/1     1            1           14h

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/mongodb-kubernetes-operator-74965cfd5d   1         1         1       14h

NAME                               READY   AGE
statefulset.apps/mongodb-dev       0/3     14h
statefulset.apps/mongodb-dev-arb   0/0     14h
```

The logs from the kubernetes operator:

```
2023-09-27T00:57:09.456Z        INFO    controllers/replica_set_controller.go:139       Reconciling MongoDB     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.456Z        DEBUG   controllers/replica_set_controller.go:141       Validating MongoDB.Spec {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.456Z        DEBUG   controllers/replica_set_controller.go:151       Ensuring the service exists     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.456Z        DEBUG   agent/agent_readiness.go:110    The Agent in the Pod 'mongodb-dev-0' hasn't reached the goal state yet (goal: 1, agent: -1)     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.456Z        DEBUG   agent/replica_set_port_manager.go:122   No port change required {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.461Z        INFO    controllers/replica_set_controller.go:470       Create/Update operation succeeded       {"ReplicaSet": "mongodb/mongodb-dev", "operation": "updated"}
2023-09-27T00:57:09.462Z        INFO    controllers/replica_set_controller.go:362       Creating/Updating AutomationConfig      {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.472Z        DEBUG   scram/scram.go:172      Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2023-09-27T00:57:09.472Z        DEBUG   agent/agent_readiness.go:110    The Agent in the Pod 'mongodb-dev-0' hasn't reached the goal state yet (goal: 1, agent: -1)     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.472Z        DEBUG   agent/replica_set_port_manager.go:122   No port change required {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.472Z        DEBUG   agent/replica_set_port_manager.go:40    Calculated process port map: map[mongodb-dev-0:27017 mongodb-dev-1:27017 mongodb-dev-2:27017]   {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.472Z        DEBUG   controllers/replica_set_controller.go:537       AutomationConfigMembersThisReconciliation       {"mdb.AutomationConfigMembersThisReconciliation()": 3}
2023-09-27T00:57:09.473Z        DEBUG   controllers/replica_set_controller.go:385       Waiting for agents to reach version 1   {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.473Z        DEBUG   agent/agent_readiness.go:110    The Agent in the Pod 'mongodb-dev-0' hasn't reached the goal state yet (goal: 1, agent: -1)     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:09.473Z        INFO    controllers/mongodb_status_options.go:110       ReplicaSet is not yet ready, retrying in 10 seconds
2023-09-27T00:57:19.479Z        INFO    controllers/replica_set_controller.go:139       Reconciling MongoDB     {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:19.479Z        DEBUG   controllers/replica_set_controller.go:141       Validating MongoDB.Spec {"ReplicaSet": "mongodb/mongodb-dev"}
2023-09-27T00:57:19.479Z        DEBUG   controllers/replica_set_controller.go:151       Ensuring the service exists     {"ReplicaSet": "mongodb/mongodb-dev"}
```

**Comment by irajdeep** [comment]
Hey there 

I noticed you're trying to deploy server version `7.0.1`. MongoDB deployment with server version >= 7.0 is currently not supported by the community operator. We are working on adding this support to the community operator soon.

**Comment by FlaxHaxx** [comment]
I have also tried with 6.0.5 as the documentation suggests but get the same error. This `Event` is from the MongoDB pod.

```
  Normal   Pulled     6s (x2 over 13s)  kubelet            Container image "docker.io/mongodb/mongodb-community-server:6.0.5-ubi8" already present on machine
  Warning  Unhealthy  5s (x3 over 6s)   kubelet            Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory

goroutine 1 [running]:
main.main()
           /workspace/cmd/readiness/main.go:226 +0x19a
  Warning  BackOff    1s (x2 over 2s)  kubelet  Back-off restarting failed container mongod in pod mongodb-dev-0_mongodb(8642484c-7be7-413b-ac77-d5e9189a9f57)
  Warning  Unhealthy  1s (x2 over 2s)  kubelet  Readiness probe failed:

```

**Comment by FlaxHaxx** [comment]
It's working with operator version `v0.7.6` and mongodb version `4.2.6`

It's not working with operator version `v0.8.2` and mongodb version `4.2.6`.

It's not working with operator version `v0.7.6` and mongodb version `6.0.5`.
