### ISSUE TITLE
Mongodb-agent is never ready - 

### ISSUE THREAD

**Issue by DamienGH** [mongodb/mongodb-kubernetes-operator#1418]
**What did you do to encounter the bug?**
1. Deploy manager v0.8.2 
2. then MongoDBCommunity v6.0.5

**What did you expect?**
Mongodb-agent ready and cluster OK

**What happened instead?**
Side container mongodb-agent is never go to ready state. Errors : 
- Readiness probe failed: command "/opt/scripts/readinessprobe" timed out
- In the mongodbagent log : "Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: no such file or directory goroutine 1 [running]: main.main() /workspace/cmd/readiness/main.go:226"
- In the mongodbagent log with readiness probe v1.0.17 instead of v1.0.15 : cat: /mongodb-automation/agent-api-key/agentApiKey: No such file or directory

**Operator Information**
 - Operator Version : 0.8.2
 - MongoDB Image used : 6.0.5

**Kubernetes Cluster Information**
 - Distribution : tkgi
 - Version : 1.24
 - Image Registry location (quay, or an internal registry) : quay

**Additional context**
We try to up the readinessprobe version from 1.0.15 to 1.0.17 but we have the same problem

If possible, please include:

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replicaset
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: user-admin
      db: mydb
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: user-admin-mongo-secret
        key: MONGO_PASSWORD
      roles:
        - name: clusterAdmin
          db: mydb
        - name: dbOwner
          db: mydb
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "200m"
                  memory: 500M
                requests:
                  cpu: "50m"
                  memory: 100M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "200m"
                  memory: 250M
                requests:
                  cpu: "50m"
                  memory: 50M
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
```

 - log files for the operator and database pods
```
Running ./manager
2023-10-26T14:36:16.874Z	INFO	manager/main.go:74	Watching namespace: my-namespace
I1026 14:36:17.925053       8 request.go:690] Waited for 1.03553922s due to client-side throttling, not priority and fairness, request: GET:https://56.0.0.1:443/apis/tap.linkerd.io/v1alpha1?timeout=32s
2023-10-26T14:36:20.635Z	INFO	manager/main.go:91	Registering Components.
2023-10-26T14:36:20.635Z	INFO	manager/main.go:104	Starting the Cmd.
2023-10-26T14:36:20.737Z	INFO	controllers/replica_set_controller.go:139	Reconciling MongoDB	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:20.737Z	DEBUG	controllers/replica_set_controller.go:141	Validating MongoDB.Spec	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:20.737Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:20.838Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:20.939Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.041Z	INFO	controllers/replica_set_controller.go:470	Create/Update operation succeeded	{"ReplicaSet": "my-namespace/mongodb-replicaset", "operation": "updated"}
2023-10-26T14:36:21.041Z	INFO	controllers/replica_set_controller.go:362	Creating/Updating AutomationConfig	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	DEBUG	scram/scram.go:172	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2023-10-26T14:36:21.055Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	DEBUG	agent/replica_set_port_manager.go:40	Calculated process port map: map[ds042-mongodb-replicaset-0:27017]	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	DEBUG	controllers/replica_set_controller.go:537	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 1}
2023-10-26T14:36:21.055Z	DEBUG	controllers/replica_set_controller.go:385	Waiting for agents to reach version 3	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.055Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
2023-10-26T14:36:21.063Z	INFO	controllers/replica_set_controller.go:139	Reconciling MongoDB	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.063Z	DEBUG	controllers/replica_set_controller.go:141	Validating MongoDB.Spec	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.063Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.063Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.063Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.167Z	INFO	controllers/replica_set_controller.go:470	Create/Update operation succeeded	{"ReplicaSet": "my-namespace/mongodb-replicaset", "operation": "updated"}
2023-10-26T14:36:21.167Z	INFO	controllers/replica_set_controller.go:362	Creating/Updating AutomationConfig	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	DEBUG	scram/scram.go:172	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2023-10-26T14:36:21.180Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	DEBUG	agent/replica_set_port_manager.go:40	Calculated process port map: map[ds042-mongodb-replicaset-0:27017]	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	DEBUG	controllers/replica_set_controller.go:537	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 1}
2023-10-26T14:36:21.180Z	DEBUG	controllers/replica_set_controller.go:385	Waiting for agents to reach version 3	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:21.180Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
2023-10-26T14:36:31.064Z	INFO	controllers/replica_set_controller.go:139	Reconciling MongoDB	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.064Z	DEBUG	controllers/replica_set_controller.go:141	Validating MongoDB.Spec	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.064Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.064Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.064Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.181Z	INFO	controllers/replica_set_controller.go:470	Create/Update operation succeeded	{"ReplicaSet": "my-namespace/mongodb-replicaset", "operation": "updated"}
2023-10-26T14:36:31.181Z	INFO	controllers/replica_set_controller.go:362	Creating/Updating AutomationConfig	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.194Z	DEBUG	scram/scram.go:172	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2023-10-26T14:36:31.194Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.194Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.194Z	DEBUG	agent/replica_set_port_manager.go:40	Calculated process port map: map[ds042-mongodb-replicaset-0:27017]	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.194Z	DEBUG	controllers/replica_set_controller.go:537	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 1}
2023-10-26T14:36:31.195Z	DEBUG	controllers/replica_set_controller.go:385	Waiting for agents to reach version 3	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.195Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:31.195Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
2023-10-26T14:36:38.234Z	INFO	controllers/replica_set_controller.go:139	Reconciling MongoDB	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.234Z	DEBUG	controllers/replica_set_controller.go:141	Validating MongoDB.Spec	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.235Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.235Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.235Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.359Z	INFO	controllers/replica_set_controller.go:470	Create/Update operation succeeded	{"ReplicaSet": "my-namespace/mongodb-replicaset", "operation": "updated"}
2023-10-26T14:36:38.359Z	INFO	controllers/replica_set_controller.go:362	Creating/Updating AutomationConfig	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	DEBUG	scram/scram.go:172	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2023-10-26T14:36:38.371Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	DEBUG	agent/replica_set_port_manager.go:122	No port change required	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	DEBUG	agent/replica_set_port_manager.go:40	Calculated process port map: map[ds042-mongodb-replicaset-0:27017]	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	DEBUG	controllers/replica_set_controller.go:537	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 1}
2023-10-26T14:36:38.371Z	DEBUG	controllers/replica_set_controller.go:385	Waiting for agents to reach version 3	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:38.371Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
2023-10-26T14:36:41.203Z	INFO	controllers/replica_set_controller.go:139	Reconciling MongoDB	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:41.203Z	DEBUG	controllers/replica_set_controller.go:141	Validating MongoDB.Spec	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:41.203Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
2023-10-26T14:36:41.203Z	DEBUG	agent/agent_readiness.go:106	The Pod 'ds042-mongodb-replicaset-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "my-namespace/mongodb-replicaset"}
```

**Comment by vinnytwice** [comment]
@DamienGH Hi, I'm having troubles too.  I 'm installing the same chart on Hetzner vm (arm) and on a k3d cluster on my MacBook M1 and it fails only on my local cluster..

**Comment by vinnytwice** [comment]
@DamienGH, today I was finally able to install mongo v. 6.0.11 in a k3d Kubernetes cluster on my MacBook with M1 chip.
Mongo is installed via the operator , which on arm machines still does have a problem as the mongo-agent it installs doesn't have an arm64 image yet. I used these images https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-1666717878 to override chart's values and installed the 6.0.11 version without problems ( see the chart's values here https://github.com/mongodb/mongodb-kubernetes-operator/issues/1420#issuecomment-1790885017). 
So let's hope that the agent arm64 image gets uploaded to quay.io soon so to use the official operator.
Cheers

**Comment by DamienGH** [comment]
Hi @vinnytwice,
thanks for the suggestion but my clusters ar not with ARM64 chips (Intel Xeon Gold 6242R).
But I still tested with mohsinonxrm images and it fails with same errors.
So we are still blocked and we will give up on mongodb community operator at the end of the week. Too bad :(

**Comment by VoxoLone** [comment]
Had the same problem. Because of this issue, I tried it on x86 and the replicaset started like a charm.

**Comment by VoxoLone** [comment]
Is there an alternative registry for quay.io that supports arm for the agent etc?

**Comment by Julien-Ben** [comment]
Hello @VoxoLone 
Agent images are now available for both ARM and x86 architectures.
You can find them here : [](https://quay.io/repository/mongodb/mongodb-agent-ubi?tab=tags)
