### ISSUE TITLE
quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1 has wrong architecture of binaries

### ISSUE THREAD

**Issue by camaeel** [mongodb/mongodb-kubernetes-operator#1588]
**What did you do to encounter the bug?**
1. Execute on ARM machine (M1 Macbook with lima-vm) `docker run --rm -it quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1`
2. Output is: 
    ```
    exec /agent/mongodb-agent: exec format error
    ```
When I inspect the image it says it is arm64 image, but the binary `/agent/mongodb-agent` seems to have wrong format

**What did you expect?**
Arm64 image runs properly on this architecture

**What happened instead?**
`exec /agent/mongodb-agent: exec format error`

**Operator Information**
 - Operator version: quay.io/mongodb/mongodb-kubernetes-operator:0.10.0
 - MongoDB Image used: quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1

**Kubernetes Cluster Information**
 - Distribution: Kind
 - Version: v1.30.0
 - Image Registry location: quay

**Comment by mdkcore0** [comment]
we are facing this issue with some coworkers that use M1 laptops

as workaround we are forcing an arm64 image tag for now

**Comment by nammn** [comment]
This might fix it: https://github.com/mongodb/mongodb-kubernetes-operator/pull/1589/files#diff-40aac11a56bed8a174eee47f4cdcb63eb10445afa84b38f2145a331914941bcb

**Comment by nammn** [comment]
@camaeel @mdkcore0 thanks a lot for flagging this. I've verified the fix and released the image "anew". It should work now

```
❯ docker run --rm -it --platform linux/arm64 --entrypoint sh quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1
Unable to find image 'quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1' locally
107.0.1.8507-1: Pulling from mongodb/mongodb-agent-ubi
97fbbb377915: Already exists
fcb268d47b35: Pull complete
d0aceba60afc: Pull complete
f82ced22f5e0: Pull complete
8fdf9492dcc0: Pull complete
005595b2c510: Pull complete
8f7673eb21a5: Pull complete
410ffb688cc4: Pull complete
524d8c45606c: Pull complete
f37f2c4de31a: Pull complete
a3c2632f1afa: Pull complete
Digest: sha256:a93a37b585d5a455f66021e6c0e62c90fd8861d9d7e085f2444d44f955efd64c
Status: Downloaded newer image for quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1
sh-4.4$ ls /var/lib/
alternatives/           dbus/                   games/                  mongodb-mms-automation/ portables/              rpm/                    selinux/
automation/             dnf/                    misc/                   net-snmp/               private/                rpm-state/              systemd/
sh-4.4$ ls /var/lib/mongodb-mms-automation/
mongodb-database-tools-rhel82-aarch64-100.9.4
sh-4.4$ ./agent/mongodb-agent
panic: Failed to get current user: user: unknown userid 2000

goroutine 1 [running]:
com.tengen/cm/util.init.4()
	/data/mci/0a9c462c5ee9ac18e0c82a81f0a89600/mms-automation/build/go-dependencies/src/util/user.go:14 +0x98



❯ docker run --rm -it --platform linux/amd64 --entrypoint sh quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1
Unable to find image 'quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1' locally
107.0.1.8507-1: Pulling from mongodb/mongodb-agent-ubi
a15b996d0c1b: Already exists
bde4249d1bc9: Pull complete
17ab3bb93f65: Pull complete
bbff651da1c4: Pull complete
9019ae4e7434: Pull complete
0f07ba23a400: Pull complete
c2b71dbc2a3d: Pull complete
6e0906f9c3ab: Pull complete
764540c8eb7e: Pull complete
317954554f39: Pull complete
731586cf71f3: Pull complete
Digest: sha256:a93a37b585d5a455f66021e6c0e62c90fd8861d9d7e085f2444d44f955efd64c
Status: Downloaded newer image for quay.io/mongodb/mongodb-agent-ubi:107.0.1.8507-1
sh-4.4$ ls /var/lib/mongodb-mms-automation/
mongodb-database-tools-rhel70-x86_64-100.9.4
sh-4.4$ ./agent/mongodb-agent
panic: Failed to get current user: user: unknown userid 2000

goroutine 1 [running]:
com.tengen/cm/util.init.4()
	/data/mci/5b0ec09538efa78a489b2ca0b1c125cd/mms-automation/build/go-dependencies/src/util/user.go:14 +0x94
```
