### ISSUE TITLE
After updating operator 0.5.1 to 0.5.2 all mongodb object became Pending status

### ISSUE THREAD

**Issue by ossinkine** [mongodb/mongodb-kubernetes-operator#426]
**What did you do to encounter the bug?**
After updating operator 0.5.1 to 0.5.2 all mongodb object became Pending status.
Operator log contains:
```
2021-04-13T13:52:53.621Z        INFO    controllers/replica_set_controller.go:124       Reconciling MongoDB     {"ReplicaSet": "example/mongodb", "MongoDB.Spec": {"members":3,"type":"ReplicaSet","version":"4.4.4","featureCompatibilityVersion":"4.4","security":{"authentication":{"modes":["SCRAM"],"ignoreUnknownUsers":null},"tls":{"enabled":false,"optional":false,"certificateKeySecretRef":{"name":""},"caConfigMapRef":{"name":""}}},"users":[{"name":"example","db":"admin","passwordSecretRef":{"name":"mongodb-password","key":""},"roles":[{"db":"example","name":"readWrite"}],"scramCredentialsSecretName":"mongodb-scram"}],"statefulSet":{"spec":{}},"additionalMongodConfig":{}}, "MongoDB.Status": {"mongoUri":"mongodb://mongodb-0.mongodb-svc.example.svc.cluster.local:27017,mongodb-1.mongodb-svc.example.svc.cluster.local:27017,mongodb-2.mongodb-svc.example.svc.cluster.local:27017","phase":"Pending","currentStatefulSetReplicas":3,"currentMongoDBMembers":3,"message":"ReplicaSet is not yet ready, retrying in 10 seconds"}}
2021-04-13T13:52:53.621Z        DEBUG   controllers/replica_set_controller.go:126       Validating MongoDB.Spec {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.621Z        DEBUG   controllers/replica_set_controller.go:135       Ensuring the service exists     {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.647Z        INFO    controllers/replica_set_controller.go:375       The service already exists... moving forward: services "mongodb-svc" already exists        {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.648Z        INFO    controllers/replica_set_controller.go:298       Creating/Updating AutomationConfig      {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.678Z        DEBUG   scram/scram.go:160      Credentials have not changed, using credentials stored in: secret/mongodb-scram-scram-credentials
2021-04-13T13:52:53.678Z        DEBUG   controllers/replica_set_controller.go:414       AutomationConfigMembersThisReconciliation       {"mdb.AutomationConfigMembersThisReconciliation()": 3}
2021-04-13T13:52:53.679Z        DEBUG   controllers/replica_set_controller.go:316       Waiting for agents to reach version 746 {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.679Z        DEBUG   agent/agent_readiness.go:61     The Pod 'mongodb-0' doesn't have annotation 'agent.mongodb.com/version' yet     {"ReplicaSet": "example/mongodb"}
2021-04-13T13:52:53.679Z        INFO    controllers/mongodb_status_options.go:90        ReplicaSet is not yet ready, retrying in 10 seconds
```

**What did you expect?**
Operator successfully updated, all mongodb objects continue work

**What happened instead?**
Operator successfully updated, all mongodb objects became Pending status

`kubectl describe pod operator`:
```
Name:         mongodb-kubernetes-operator-d7767954f-zrt5v
Namespace:    mongodb-operator
Priority:     0
Node:         gke-default-pool-18-cceda911-8mm6/10.10.16.24
Start Time:   Tue, 13 Apr 2021 13:38:44 +0000
Labels:       name=mongodb-kubernetes-operator
              pod-template-hash=d7767954f
Annotations:  cni.projectcalico.org/podIP: 10.32.1.174/32
Status:       Running
IP:           10.32.1.174
IPs:
  IP:           10.32.1.174
Controlled By:  ReplicaSet/mongodb-kubernetes-operator-d7767954f
Containers:
  mongodb-kubernetes-operator:
    Container ID:  containerd://89ef2f8fb945af814dddab0b816e633c7dd1645a7cf6162890a846bd14ee0b91
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.5.2
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator@sha256:3ea8935ce639ef43ca1aa25ff244719a163d6e081f398674eb678f8bd475bdfa
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/entrypoint
    State:          Running
      Started:      Tue, 13 Apr 2021 13:38:45 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:             *
      POD_NAME:                    mongodb-kubernetes-operator-d7767954f-zrt5v (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:10.27.0.6772-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      READINESS_PROBE_IMAGE:       quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1
      MONGODB_IMAGE:               library/mongo
      MONGODB_REPO_URL:            registry.hub.docker.com
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-mb289 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  mongodb-kubernetes-operator-token-mb289:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-kubernetes-operator-token-mb289
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  18m   default-scheduler  Successfully assigned mongodb-operator/mongodb-kubernetes-operator-d7767954f-zrt5v to gke-default-pool-18-cceda911-8mm6
  Normal  Pulling    18m   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator:0.5.2"
  Normal  Pulled     18m   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.5.2"
  Normal  Created    18m   kubelet            Created container mongodb-kubernetes-operator
  Normal  Started    18m   kubelet            Started container mongodb-kubernetes-operator
```

`kubectl describe mdbc`:
```
Name:         mongodb
Namespace:    example
Labels:       <none>
Annotations:  mongodb.com/v1.hasLeftReadyStateAnnotationKey: false
              mongodb.com/v1.lastSuccessfulConfiguration:
                {"members":3,"type":"ReplicaSet","version":"4.4.4","featureCompatibilityVersion":"4.4","security":{"authentication":{"modes":["SCRAM"]},"t...
              mongodb.com/v1.lastVersion: 4.4.4
API Version:  mongodbcommunity.mongodb.com/v1
Kind:         MongoDBCommunity
Metadata:
  Creation Timestamp:  2021-04-13T11:08:49Z
  Generation:          7
  Managed Fields:
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:featureCompatibilityVersion:
        f:members:
        f:security:
          .:
          f:authentication:
            .:
            f:modes:
        f:statefulSet:
          .:
          f:spec:
            .:
            f:template:
              .:
              f:spec:
                .:
                f:affinity:
                  .:
                  f:podAntiAffinity:
                    .:
                    f:preferredDuringSchedulingIgnoredDuringExecution:
                    f:requiredDuringSchedulingIgnoredDuringExecution:
        f:type:
        f:version:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-04-13T13:42:00Z
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:mongodb.com/v1.hasLeftReadyStateAnnotationKey:
          f:mongodb.com/v1.lastSuccessfulConfiguration:
          f:mongodb.com/v1.lastVersion:
      f:spec:
        f:additionalMongodConfig:
        f:security:
          f:authentication:
            f:ignoreUnknownUsers:
          f:tls:
            .:
            f:caConfigMapRef:
              .:
              f:name:
            f:certificateKeySecretRef:
              .:
              f:name:
            f:enabled:
            f:optional:
        f:statefulSet:
          f:spec:
            f:selector:
            f:serviceName:
            f:template:
              f:metadata:
                .:
                f:creationTimestamp:
              f:spec:
                f:containers:
            f:updateStrategy:
            f:volumeClaimTemplates:
        f:users:
      f:status:
        .:
        f:currentMongoDBMembers:
        f:currentStatefulSetReplicas:
        f:message:
        f:mongoUri:
        f:phase:
    Manager:         manager
    Operation:       Update
    Time:            2021-04-13T13:42:00Z
  Resource Version:  315872932
  Self Link:         /apis/mongodbcommunity.mongodb.com/v1/namespaces/example/mongodbcommunity/mongodb
  UID:               700d4723-265f-4fdd-89f6-8b7403448efe
Spec:
  Additional Mongod Config:       <nil>
  Feature Compatibility Version:  4.4
  Members:                        3
  Security:
    Authentication:
      Modes:
        SCRAM
    Tls:
      Ca Config Map Ref:
        Name:
      Certificate Key Secret Ref:
        Name:
      Enabled:   false
      Optional:  false
  Stateful Set:
    Spec:
      Selector:      <nil>
      Service Name:
      Template:
        Metadata:
          Creation Timestamp:  <nil>
        Spec:
          Affinity:
            Pod Anti Affinity:
              Preferred During Scheduling Ignored During Execution:
                Pod Affinity Term:
                  Label Selector:
                    Match Labels:
                      App:       mongodb-svc
                  Topology Key:  topology.kubernetes.io/zone
                Weight:          100
              Required During Scheduling Ignored During Execution:
                Label Selector:
                  Match Labels:
                    App:       mongodb-svc
                Topology Key:  kubernetes.io/hostname
          Containers:
            Name:  mongod
            Resources:
              Limits:
                Cpu:     1
                Memory:  1Gi
              Requests:
                Cpu:     250m
                Memory:  256Mi
            Name:        mongodb-agent
            Resources:
              Limits:
                Cpu:     250m
                Memory:  64Mi
              Requests:
                Cpu:     50m
                Memory:  16Mi
      Update Strategy:
      Volume Claim Templates:
        Metadata:
          Name:  data-volume
        Spec:
          Resources:
            Requests:
              Storage:         8Gi
          Storage Class Name:  mongodb-data-volume
  Type:                        ReplicaSet
  Users:
    Db:    admin
    Name:  example
    Password Secret Ref:
      Name:  mongodb-password
    Roles:
      Db:                           example
      Name:                         readWrite
    Scram Credentials Secret Name:  mongodb-scram
  Version:                          4.4.4
Status:
  Current Mongo DB Members:       3
  Current Stateful Set Replicas:  3
  Message:                        ReplicaSet is not yet ready, retrying in 10 seconds
  Mongo Uri:                      mongodb://mongodb-0.mongodb-svc.example.svc.cluster.local:27017,mongodb-1.mongodb-svc.example.svc.cluster.local:27017,mongodb-2.mongodb-svc.example.svc.cluster.local:27017
  Phase:                          Pending
Events:                           <none>
```

**Comment by bznein** [comment]
Hi @ossinkine 

Can you please attach the content of the file in the following path: `/var/log/mongodb-mms-automation/agent-health-status.json` for all pods?

Thanks

**Comment by ossinkine** [comment]
If you mean `mongodb-agent` container of `monogdb-0` pod there is no such file:
```
# ls -la /var/log/mongodb-mms-automation
total 180
drwxr-xr-x 1 root root   4096 Apr 13 11:09 .
drwxr-xr-x 1 root root   4096 Feb 17 16:44 ..
drwxrwxrwx 2 root root   4096 Apr 13 14:17 healthstatus
-rw-rw-rw- 1 root root 159204 Apr 13 14:17 readiness.log
```

**Comment by bznein** [comment]
Hi @ossinkine, sorry I might have confused filepaths. Can you please attach both `healthstatus` and `readiness.log` here? (for a single pod is enough)

**Comment by ossinkine** [comment]
I've cut duplicate lines
```
# cat /var/log/mongodb-mms-automation/readiness.log
2021-04-13T11:09:43.234Z        DEBUG   probe/readiness.go:217  Automation Config version: 1, Agent last version: 1
...
2021-04-13T13:16:23.236Z        DEBUG   probe/readiness.go:217  Automation Config version: 15, Agent last version: 1
2021-04-13T13:16:23.236Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T11:10:18Z
2021-04-13T13:16:33.233Z        DEBUG   probe/readiness.go:217  Automation Config version: 74, Agent last version: 1
2021-04-13T13:16:33.271Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T11:10:18Z
2021-04-13T13:16:43.311Z        DEBUG   probe/readiness.go:217  Automation Config version: 136, Agent last version: 1
2021-04-13T13:16:43.311Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T11:10:18Z
2021-04-13T13:16:53.278Z        DEBUG   probe/readiness.go:217  Automation Config version: 188, Agent last version: 1
2021-04-13T13:16:53.278Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T11:10:18Z
2021-04-13T13:17:03.272Z        DEBUG   probe/readiness.go:217  Automation Config version: 188, Agent last version: 159
2021-04-13T13:17:03.272Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T11:10:18Z
...
2021-04-13T13:18:23.573Z        DEBUG   probe/readiness.go:217  Automation Config version: 188, Agent last version: 159
...
2021-04-13T13:31:03.271Z        DEBUG   probe/readiness.go:217  Automation Config version: 473, Agent last version: 473
...
2021-04-13T13:38:53.243Z        DEBUG   probe/readiness.go:217  Automation Config version: 525, Agent last version: 473
2021-04-13T13:38:53.243Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T13:30:49Z
2021-04-13T13:39:03.224Z        DEBUG   probe/readiness.go:217  Automation Config version: 611, Agent last version: 473
2021-04-13T13:39:03.224Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T13:30:49Z
2021-04-13T13:39:13.304Z        DEBUG   probe/readiness.go:217  Automation Config version: 710, Agent last version: 473
2021-04-13T13:39:13.304Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T13:30:49Z
2021-04-13T13:39:23.272Z        DEBUG   probe/readiness.go:217  Automation Config version: 746, Agent last version: 473
2021-04-13T13:39:23.272Z        DEBUG   probe/readiness.go:136  The Agent hasn't reported working on the new config yet, the last plan finished at 2021-04-13T13:30:49Z
...
```
```
# cat /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
{"statuses":{"mongodb-0":{"IsInGoalState":false,"LastMongoUpTime":1618323900,"ExpectedToBeUp":true,"ReplicationStatus":1}},"mmsStatus":{"mongodb-0":{"name":"mongodb-0","lastGoalVersionAchieved":473,"plans":[{"started":"2021-04-13T11:10:16.682059987Z","completed":"2021-04-13T11:10:18.275738028Z","moves":[{"move":"EnsureAutomationCredentials","moveDoc":"Ensure the automation user exists","steps":[{"step":"EnsureAutomationCredentials","stepDoc":"Ensure the automation user exists","isWaitStep":false,"started":"2021-04-13T11:10:16.682085561Z","completed":"2021-04-13T11:10:17.780062674Z","result":"success"}]},{"move":"AdjustUsers","moveDoc":"Adjust Users","steps":[{"step":"AdjustUsers","stepDoc":"Adjust Users","isWaitStep":false,"started":"2021-04-13T11:10:17.78023974Z","completed":"2021-04-13T11:10:18.275550251Z","result":"success"}]}]},{"started":"2021-04-13T13:18:11.777123746Z","completed":"2021-04-13T13:30:49.685344938Z","moves":[{"move":"Download","moveDoc":"Download mongodb binaries","steps":[{"step":"Download","stepDoc":"Download mongodb binaries (may take a while)","isWaitStep":false,"started":"2021-04-13T13:18:11.777187937Z","completed":null,"result":"error"}]},{"move":"BounceChangeArgs","moveDoc":"Bounce restart following arguments change","steps":[{"step":"CheckNeedsBounceRestart","stepDoc":"Check if restart is needed","isWaitStep":false,"started":null,"completed":null,"result":""},{"step":"WaitCanBounceStop","stepDoc":"Wait until bounce restart is possible","isWaitStep":true,"started":null,"completed":null,"result":""},{"step":"BounceStop","stepDoc":"Stop the process","isWaitStep":false,"started":null,"completed":null,"result":""}]},{"move":"WaitCanStartFresh","moveDoc":"Wait until process can start up","steps":[{"step":"WaitCanStartFresh","stepDoc":"Wait until process can start up","isWaitStep":true,"started":null,"completed":null,"result":""}]},{"move":"Start","moveDoc":"Start the process","steps":[{"step":"StartFresh","stepDoc":"Start a mongo instance  (start fresh)","isWaitStep":false,"started":null,"completed":null,"result":""}]},{"move":"EnsureAutomationCredentials","moveDoc":"Ensure the automation user exists","steps":[{"step":"EnsureAutomationCredentials","stepDoc":"Ensure the automation user exists","isWaitStep":false,"started":null,"completed":null,"result":""}]}]}],"errorCode":0,"errorString":"\u003cmongodb-0\u003e [14:24:49.493] Plan execution failed on step Download as part of move Download : \u003cmongodb-0\u003e [14:24:49.493] Failed to apply action. Result = \u003cnil\u003e : \u003cmongodb-0\u003e [14:24:49.492] Error getting DownloadMongoDBBinary url for this host -- should not be empty"}}}
```

**Comment by ossinkine** [comment]
I'm trying to set up a new mongodb cluster with the operator 0.5.2 but pod can't start:
```
$ kubectl logs mongodb-0 -c mongodb-agent
2000
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:102:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:103:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:104:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:105:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
mongodb:x:2000:0:,,,:/:/bin/bash
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
panic: Failed to get current user: user: unknown userid 2000

goroutine 1 [running]:
com.tengen/cm/util.init.3()
        /data/mci/3b33adea1aa7936aed34816994fa0f41/mms-automation/build/go-dependencies/src/util/user.go:14 +0xe5
```

```
$ kubectl describe pod mongodb-0
Name:         mongodb-0
Namespace:    example
Priority:     0
Node:         gke-default-pool-18-ed39b27c-fmq7/10.10.16.22
Start Time:   Wed, 14 Apr 2021 08:32:34 +0000
Labels:       app=mongodb-svc
              controller-revision-hash=mongodb-99597dcfd
              statefulset.kubernetes.io/pod-name=mongodb-0
Annotations:  cni.projectcalico.org/podIP: 10.32.3.222/32
Status:       Running
IP:           10.32.3.222
IPs:
  IP:           10.32.3.222
Controlled By:  StatefulSet/mongodb
Init Containers:
  mongod-posthook:
    Container ID:  containerd://f97e327886c8c948e86bc825198bf25bd603a42a758211a43b94071cc23d7adc
    Image:         quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook@sha256:e99105b1c54e12913ddaf470af8025111a6e6e4c8917fc61be71d1bc0328e7d7
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      version-upgrade-hook
      /hooks/version-upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 14 Apr 2021 08:32:52 +0000
      Finished:     Wed, 14 Apr 2021 08:32:52 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-sjvxw (ro)
  mongodb-agent-readinessprobe:
    Container ID:  containerd://f77a9bf482c801659f520944020815bc6da5a264068495216c2f308857838b35
    Image:         quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1
    Image ID:      quay.io/mongodb/mongodb-kubernetes-readinessprobe@sha256:d5bc703b78f23ed1b84581944f0a2bc73f4b37896b8daaacbbc35f32032e6447
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /probes/readinessprobe
      /opt/scripts/readinessprobe
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 14 Apr 2021 08:32:55 +0000
      Finished:     Wed, 14 Apr 2021 08:32:55 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/scripts from agent-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-sjvxw (ro)
Containers:
  mongod:
    Container ID:  containerd://202891df2928d7d26559a1f83cc4386b9e2ee04a89d7f5a2c183d891250685f0
    Image:         registry.hub.docker.com/library/mongo:4.4.4
    Image ID:      registry.hub.docker.com/library/mongo@sha256:75a5f624bd6d14254e0d84c2833f576109672750aaf2bf01d61cb5ead44f4505
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c

      #run post-start hook to handle version changes
      /hooks/version-upgrade

      # wait for config and keyfile to be created by the agent
       while ! [ -f /data/automation-mongod.conf -a -f /var/lib/mongodb-mms-automation/authentication/keyfile ]; do sleep 3 ; done ; sleep 2 ;


      # start mongod with this configuration
      exec mongod -f /data/automation-mongod.conf;

    State:          Running
      Started:      Wed, 14 Apr 2021 08:32:56 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     250m
      memory:  256Mi
    Environment:
      AGENT_STATUS_FILEPATH:  /healthstatus/agent-health-status.json
    Mounts:
      /data from data-volume (rw)
      /healthstatus from healthstatus (rw)
      /hooks from hooks (rw)
      /var/lib/mongodb-mms-automation/authentication from mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-sjvxw (ro)
  mongodb-agent:
    Container ID:  containerd://f3658d093783342ffc2c7cb4fc72252e3688f20ef069900dd979f1c84276cfeb
    Image:         quay.io/mongodb/mongodb-agent:10.27.0.6772-1
    Image ID:      quay.io/mongodb/mongodb-agent@sha256:00bc0c60aa7eb11494d8ff170281983a0dfa3b4378459885b5eda3129b16d4b4
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      current_uid=$(id -u)
      echo $current_uid
      declare -r current_uid
      if ! grep -q "${current_uid}" /etc/passwd ; then
      sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
      echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
      cat /tmp/passwd
      export NSS_WRAPPER_PASSWD=/tmp/passwd
      export LD_PRELOAD=libnss_wrapper.so
      export NSS_WRAPPER_GROUP=/etc/group
      fi
      agent/mongodb-agent -cluster=/var/lib/automation/config/cluster-config.json -skipMongoStart -noDaemonize -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -useLocalMongoDbTools
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 14 Apr 2021 08:38:39 +0000
      Finished:     Wed, 14 Apr 2021 08:38:39 +0000
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:     250m
      memory:  64Mi
    Requests:
      cpu:      50m
      memory:   16Mi
    Readiness:  exec [/opt/scripts/readinessprobe] delay=5s timeout=1s period=10s #success=1 #failure=60
    Environment:
      AGENT_STATUS_FILEPATH:  /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      AUTOMATION_CONFIG_MAP:  mongodb-config
      HEADLESS_AGENT:         true
      POD_NAMESPACE:          example (v1:metadata.namespace)
    Mounts:
      /data from data-volume (rw)
      /opt/scripts from agent-scripts (rw)
      /var/lib/automation/config from automation-config (ro)
      /var/lib/mongodb-mms-automation/authentication from mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/log/mongodb-mms-automation/healthstatus from healthstatus (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-sjvxw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-mongodb-0
    ReadOnly:   false
  logs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  logs-volume-mongodb-0
    ReadOnly:   false
  agent-scripts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  automation-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-config
    Optional:    false
  healthstatus:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  hooks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  mongodb-keyfile:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  mongodb-kubernetes-operator-token-sjvxw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-kubernetes-operator-token-sjvxw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        7m30s (x2 over 7m30s)  default-scheduler        0/6 nodes are available: 6 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               7m27s                  default-scheduler        Successfully assigned example/mongodb-0 to gke-default-pool-18-ed39b27c-fmq7
  Normal   SuccessfulAttachVolume  7m23s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-6f553d27-f1b6-4b0b-9dd2-a959619dbc74"
  Normal   SuccessfulAttachVolume  7m20s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a94769a1-619f-458c-8021-46d42d7fd9e7"
  Normal   Pulling                 7m10s                  kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Created                 7m9s                   kubelet                  Created container mongod-posthook
  Normal   Pulled                  7m9s                   kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Started                 7m9s                   kubelet                  Started container mongod-posthook
  Normal   Pulling                 7m8s                   kubelet                  Pulling image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1"
  Normal   Started                 7m6s                   kubelet                  Started container mongodb-agent-readinessprobe
  Normal   Pulled                  7m6s                   kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.1"
  Normal   Created                 7m6s                   kubelet                  Created container mongodb-agent-readinessprobe
  Normal   Pulled                  7m5s                   kubelet                  Container image "registry.hub.docker.com/library/mongo:4.4.4" already present on machine
  Normal   Created                 7m5s                   kubelet                  Created container mongod
  Normal   Started                 7m5s                   kubelet                  Started container mongod
  Normal   Pulling                 6m48s (x3 over 7m5s)   kubelet                  Pulling image "quay.io/mongodb/mongodb-agent:10.27.0.6772-1"
  Normal   Pulled                  6m47s (x3 over 7m5s)   kubelet                  Successfully pulled image "quay.io/mongodb/mongodb-agent:10.27.0.6772-1"
  Normal   Created                 6m47s (x3 over 7m5s)   kubelet                  Created container mongodb-agent
  Normal   Started                 6m47s (x3 over 7m5s)   kubelet                  Started container mongodb-agent
  Warning  BackOff                 2m6s (x24 over 7m3s)   kubelet                  Back-off restarting failed container
```

**Comment by bznein** [comment]
Hi @ossinkine, how did you install the operator?

Looking at the `mongodb-agent` container, it is using an old agent image that is not compatible with 0.5.2 (`quay.io/mongodb/mongodb-agent:10.27.0.6772-1`) while it should use the one specified here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/manager/manager.yaml#L35

**Comment by ossinkine** [comment]
You specified the `master` branch, I got the manifest from `0.5.2` tag: https://github.com/mongodb/mongodb-kubernetes-operator/blob/v0.5.2/config/manager/manager.yaml#L35

**Comment by bznein** [comment]
Hi @ossinkine,

it looks like we have an error with `0.5.2` tag, will fix it but in the meantime you should be able to fix that issue by using the value on `master`

**Comment by ossinkine** [comment]
Thank you, I'll return to `0.5.1` and will wait for a fix

**Comment by ossinkine** [comment]
@bznein if I use agent image from `master` (`quay.io/mongodb/mongodb-agent:10.29.0.6830-1`), the initial issue is still present, MongoDB object is in `Pending` status

**Comment by lchdev** [comment]
Hi all,

I also tried to use the operator v0.5.2 (since i'm interested in the new `ignoreUnknownUsers` flag), but I did not manage to get any mongodb cluster up and running, no matter the agent version used (from master or from 0.5.2 tag).

However, it seems to work if I install everything from current `master` branch. Would it then be possible to have a proper working tag on the latest operator version ?

**Comment by chatton** [comment]
Hi @lchdev, yes - we recently changed the user to a non-root user. This ended up causing some issues with existing deployments during an upgrade. A possible workaround is using an init container to change the permissions of the contents of the volume as per: https://github.com/mongodb/mongodb-kubernetes-operator/pull/431

**Comment by lchdev** [comment]
Hi @chatton, thanks.

I guess the patch has to be applied after upgrading the operator to v0.5.2, right ?

**Comment by chatton** [comment]
@lchdev yes, alternatively you could include this in the `spec.statefulSet.spec.template` override in the MongoDBCommunity resource.

**Comment by wpater** [comment]
Just as side note because I spent some time on deploying MongoDBCommunity on AWS EFS - if you are creating a `storageClass` for EFS then you need to specify `uid`/`gid` as `2000` to make it working.
