### ISSUE TITLE
/lib64/ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by arshabh-copods** [mongodb/mongodb-kubernetes-operator#652]
I am stuck with this issue for a long time now. Please kindly help.

I followed the documentation to install the operator and deployed config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml. However when i describe the pod i get this

I am running the operator using minikube and kind (tried both) on my apple m1 macbook air.

Any help would be highly appreciated

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  80s   default-scheduler  Successfully assigned default/example-mongodb-0 to kind-control-plane
  Normal   Pulling    80s   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2"
  Normal   Pulled     73s   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2" in 6.51282592s
  Normal   Created    73s   kubelet            Created container mongod-posthook
  Normal   Started    73s   kubelet            Started container mongod-posthook
  Normal   Pulling    72s   kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4"
  Normal   Pulled     67s   kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4" in 5.637321836s
  Normal   Created    66s   kubelet            Created container mongodb-agent-readinessprobe
  Normal   Started    66s   kubelet            Started container mongodb-agent-readinessprobe
  Normal   Pulling    66s   kubelet            Pulling image "docker.io/mongo:4.4.7"
  Normal   Pulled     35s   kubelet            Successfully pulled image "docker.io/mongo:4.4.7" in 30.878813681s
  Normal   Created    35s   kubelet            Created container mongod
  Normal   Started    35s   kubelet            Started container mongod
  Normal   Pulling    35s   kubelet            Pulling image "quay.io/mongodb/mongodb-agent:11.0.5.6963-1"
  Normal   Pulled     7s    kubelet            Successfully pulled image "quay.io/mongodb/mongodb-agent:11.0.5.6963-1" in 27.758869804s
  Normal   Created    7s    kubelet            Created container mongodb-agent
  Normal   Started    7s    kubelet            Started container mongodb-agent
  Warning  Unhealthy  0s    kubelet            Readiness probe failed: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x720 pc=0x8085c4a]

runtime stack:
runtime.throw(0x8f55b9c, 0x2a)
  /usr/local/go/src/runtime/panic.go:1116 +0x6a
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:726 +0x39a
runtime.runqput(0x0, 0x9c00380, 0x1)
  /usr/local/go/src/runtime/proc.go:5160 +0x2a
runtime.newproc.func1()
  /usr/local/go/src/runtime/proc.go:3558 +0x66
runtime.systemstack(0x80a44c4)
  /usr/local/go/src/runtime/asm_386.s:391 +0x53
runtime.mstart()
  /usr/local/go/src/runtime/proc.go:1116

goroutine 1 [running, locked to thread]:
  goroutine running on other thread; stack unavailable
```

The logs for each container are as follows

```
arshabhagarwal@Arshabhs-MacBook-Air mongodb-kubernetes-operator % kubectl logs pod/example-mongodb-0 mongod                 
/lib64/ld-linux-x86-64.so.2: No such file or directory


arshabhagarwal@Arshabhs-MacBook-Air mongodb-kubernetes-operator % kubectl logs pod/example-mongodb-0 mongodb-agent
[2021-07-22T19:44:58.601+0000] [.info] [src/util/sysdep_unix.go:LockAutomationLockFile:321] [19:44:58.600] Locking automation lock file at /tmp/mongodb-mms-automation.lock
[2021-07-22T19:44:58.608+0000] [.info] [main/components/agent.go:NewAgent:123] [19:44:58.608] Constructing new agent object with desiredClusterConfigPath=/var/lib/automation/config/cluster-config.json
[2021-07-22T19:44:58.612+0000] [.info] [src/mongosqld/custodian.go:NewCustodian:138] <mongosqld custodian> [19:44:58.612] Started
[2021-07-22T19:44:58.618+0000] [.info] [realtime/rtcollector/rtcollector.go:controlLoop:87] <rtCollector> [19:44:58.618] Starting control loop
[2021-07-22T19:44:58.619+0000] [.info] [src/kmipproxy/custodian.go:mainLoop:205] <kmipProxyMaintainer> [19:44:58.619] Starting main loop
[2021-07-22T19:44:58.618+0000] [.info] [src/dataexplorer/dataexplorer.go:controlLoop:108] <dataExplorer> [19:44:58.618] Starting control loop
[2021-07-22T19:44:58.719+0000] [.info] [main/components/agent.go:LoadClusterConfig:259] [19:44:58.719] New cluster config received! 0 (<nil>) -> 1 (2021-07-22 19:43:44.511329003 +0000 UTC)
[2021-07-22T19:44:58.720+0000] [.info] [src/modules/agents_unix.go:KillAllAgents:42] [19:44:58.720] Killing all running mongodb-mms-monitoring-agent agents at /var/lib/mongodb-mms-automation/mongodb-mms-monitoring-agent-.+\..+_.+/mongodb-mms-monitoring-agent *$
[2021-07-22T19:44:58.745+0000] [.info] [src/modules/agents_unix.go:KillAllAgents:42] [19:44:58.745] Killing all running mongodb-mms-backup-agent agents at /var/lib/mongodb-mms-automation/mongodb-mms-backup-agent-.+\..+_.+/mongodb-mms-backup-agent *$
[2021-07-22T19:44:59.076+0000] [.info] [main/components/agent.go:launchNewDirectors:555] [19:44:59.076] Launched director example-mongodb-0
[2021-07-22T19:44:59.079+0000] [.info] [realtime/rtcollector/rtcollector.go:controlLoop:95] <rtCollector> [19:44:59.079] Received new cluster config!
[2021-07-22T19:44:59.080+0000] [.info] [src/dataexplorer/dataexplorer.go:controlLoop:114] <dataExplorer> [19:44:59.079] Received new cluster config!
[2021-07-22T19:44:59.080+0000] [.info] [src/director/director.go:incorporateConfig:302] <example-mongodb-0> [19:44:59.080] clusterConfig edition is different (<nil> -> 2021-07-22 19:43:44.511329003 +0000 UTC).  Incorporating...
[2021-07-22T19:44:59.102+0000] [.info] [src/maintainers/externalmaintainer.go:mainLoop:560] [19:44:59.102] Got a new descriptor for mongot
[2021-07-22T19:44:59.102+0000] [.info] [src/maintainers/externalmaintainer.go:mainLoop:560] [19:44:59.102] Got a new descriptor for atlasProxy
SIGSEGV: segmentation violation
PC=0x0 m=8 sigcode=0

goroutine 55 [running]:
```

**Comment by arshabh-copods** [comment]
No help here ?

**Comment by arshabh-copods** [comment]
Any help would be highly appreciated. Thanks.

**Comment by jamesbroadhead** [comment]
Thanks for filing! 
We are waiting for a dependency before we can support M1 / aarch64 / arm64 machines. 
Follow #299 for details.
