### ISSUE TITLE
Readiness probe failed - permission denied

### ISSUE THREAD

**Issue by Brice187** [mongodb/mongodb-kubernetes-operator#692]
**What did you do to encounter the bug?**

Upgraded yaml and images from operator 0.5.1 to 0.7.0

**What did you expect?**
Spin up a 3-Node MongoDB ReplicaSet

**What happened instead?**
```
Readiness probe failed: panic: open /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json: permission denied goroutine 1 [running]: main.main() /build/main.go:207 +0x2eb
```

**Operator Information**
 - mongodb-kubernetes-operator:0.7.0
 - 4.4.8

**Kubernetes Cluster Information**
 - k3s
 - v1.21.3+k3s1
 - internal registry

**Additional context**
Upgraded from mongodb-kubernetes-operator:0.7.0

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    email: support@mongodb.com
  labels:
    owner: mongodb
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - mongodb-kubernetes-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /usr/local/bin/entrypoint
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: mongodb-kubernetes-operator
        - name: AGENT_IMAGE
          value: registry.example.com/quay.io/mongodb/mongodb-agent:11.0.5.6963-1
        - name: VERSION_UPGRADE_HOOK_IMAGE
          value: registry.example.com/quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
        - name: READINESS_PROBE_IMAGE
          value: registry.example.com/quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4
        - name: MONGODB_IMAGE
          value: mongo
        - name: MONGODB_REPO_URL
          value: "registry.example.com"
        image: registry.example.com/quay.io/mongodb/mongodb-kubernetes-operator:0.7.0
        imagePullPolicy: Always
        name: mongodb-kubernetes-operator
        resources:
          limits:
            cpu: 1100m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 2000
      serviceAccountName: mongodb-kubernetes-operator
```

** `kubectl describe` output **
```
lars@d04:~$ devkubectl -n portal describe mongodbcommunity.mongodbcommunity.mongodb.com portaldb
Name:         portaldb
Namespace:    portal
Labels:       argocd.argoproj.io/instance=mwscan-portal-dev
Annotations:  API Version:  mongodbcommunity.mongodb.com/v1
Kind:         MongoDBCommunity
Metadata:
  Creation Timestamp:  2021-08-18T14:38:11Z
  Generation:          6
  Managed Fields:
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:currentMongoDBMembers:
        f:currentStatefulSetReplicas:
        f:message:
        f:mongoUri:
        f:phase:
    Manager:      manager
    Operation:    Update
    Time:         2021-08-18T14:38:12Z
    API Version:  mongodbcommunity.mongodb.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:argocd.argoproj.io/instance:
      f:spec:
        .:
        f:members:
        f:security:
          .:
          f:authentication:
            .:
            f:modes:
          f:tls:
            .:
            f:caConfigMapRef:
              .:
              f:name:
            f:certificateKeySecretRef:
              .:
              f:name:
            f:enabled:
            f:optional:
        f:statefulSet:
          .:
          f:spec:
            .:
            f:template:
              .:
              f:metadata:
                .:
                f:labels:
                  .:
                  f:name:
            f:volumeClaimTemplates:
        f:type:
        f:users:
        f:version:
    Manager:         argocd-application-controller
    Operation:       Update
    Time:            2021-08-20T05:21:22Z
  Resource Version:  20763537
  UID:               cefe81d3-56e9-458b-98db-799c58600516
Spec:
  Members:  3
  Security:
    Authentication:
      Modes:
        SCRAM
    Tls:
      Ca Config Map Ref:
        Name:  mwscan-tls-ca-configmap
      Certificate Key Secret Ref:
        Name:    portal-tls-secret
      Enabled:   true
      Optional:  true
  Stateful Set:
    Spec:
      Template:
        Metadata:
          Labels:
            Name:  portaldb
      Volume Claim Templates:
        Metadata:
          Name:  data-volume
        Spec:
          Access Modes:
            ReadWriteOnce
          Resources:
            Requests:
              Storage:         1Gi
          Storage Class Name:  longhorn
  Type:                        ReplicaSet
  Users:
    Db:    admin
    Name:  mongoadmin
    Password Secret Ref:
      Name:  mongoadmin-password
    Roles:
      Db:                           admin
      Name:                         clusterAdmin
    Scram Credentials Secret Name:  mongoadmin-scram
    Db:                             portaldb
    Name:                           portaluser
    Password Secret Ref:
      Name:  portaluser-password
    Roles:
      Db:                           portaldb
      Name:                         readWrite
    Scram Credentials Secret Name:  portaluser-scram
    Db:                             portaldb
    Name:                           portaluser-ro
    Password Secret Ref:
      Name:  portaluser-ro-password
    Roles:
      Db:                           portaldb
      Name:                         readWrite
    Scram Credentials Secret Name:  portaluser-ro-scram
  Version:                          4.4.8
Status:
  Current Mongo DB Members:       0
  Current Stateful Set Replicas:  0
  Message:                        ReplicaSet is not yet ready, retrying in 10 seconds
  Mongo Uri:                      
  Phase:                          Pending
Events:                           <none>
```

 - yaml definitions for your objects
**log files for the operator and database pods**
```
lars@d04:~$ devkubectl -n portal logs pod/mongodb-kubernetes-operator-7cbc656b84-rhl8f
Running ./manager
2021-08-20T06:07:23.552Z	INFO	manager/main.go:74	Watching namespace: portal
2021-08-20T06:07:24.460Z	INFO	manager/main.go:91	Registering Components.
2021-08-20T06:07:24.461Z	INFO	manager/main.go:104	Starting the Cmd.
2021-08-20T06:07:24.566Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.566Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.566Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.580Z	INFO	controllers/replica_set_controller.go:389	The service already exists... moving forward: services "portaldb-svc" already exists	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.580Z	INFO	controllers/mongodb_tls.go:39	Ensuring TLS is correctly configured	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.681Z	INFO	controllers/mongodb_tls.go:82	Successfully validated TLS config	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.681Z	INFO	controllers/replica_set_controller.go:276	TLS is enabled, creating/updating TLS secret	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.793Z	DEBUG	controllers/replica_set_controller.go:347	Enabling TLS on an existing deployment, the StatefulSet must be updated first	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.793Z	INFO	controllers/replica_set_controller.go:287	Creating/Updating StatefulSet	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.811Z	DEBUG	controllers/replica_set_controller.go:297	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:24.811Z	INFO	controllers/mongodb_status_options.go:90	ReplicaSet is not yet ready, retrying in 10 seconds
2021-08-20T06:07:34.827Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.827Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.827Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.838Z	INFO	controllers/replica_set_controller.go:389	The service already exists... moving forward: services "portaldb-svc" already exists	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.839Z	INFO	controllers/mongodb_tls.go:39	Ensuring TLS is correctly configured	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.839Z	INFO	controllers/mongodb_tls.go:82	Successfully validated TLS config	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.839Z	INFO	controllers/replica_set_controller.go:276	TLS is enabled, creating/updating TLS secret	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.846Z	DEBUG	controllers/replica_set_controller.go:347	Enabling TLS on an existing deployment, the StatefulSet must be updated first	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.846Z	INFO	controllers/replica_set_controller.go:287	Creating/Updating StatefulSet	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.857Z	DEBUG	controllers/replica_set_controller.go:297	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "portal/portaldb"}
2021-08-20T06:07:34.857Z	INFO	controllers/mongodb_status_options.go:90	ReplicaSet is not yet ready, retrying in 10 seconds
```

no logs for database pod (-> CrashLoopBackOff)

**Comment by Brice187** [comment]
Nevermind: 

had to add 

```yaml
      volumeClaimTemplates:
...
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: longhorn
            resources:
              requests:
                storage: 2G
```
to my MongoDBCommunity StatefulSet
