### ISSUE TITLE
Operator crashes after members 1 -> 3 update

### ISSUE THREAD

**Issue by olfway** [mongodb/mongodb-kubernetes-operator#724]
**What did you do to encounter the bug?**
1. I was running one node mongodb cluster 
2. Increased members to "3" and in the same time updated "resources" in statefulSet.spec.template.spec.containers for mongod container
3. mongodb-cluster-1 pod started and become "running" but mongodb-cluster-0 pod become "pending" because of pods anti-affinity and eks node-group max nodes limit
4. Increased eks node-group limit and mongodb-cluster-0 become "running" also
5. After that noticed that mongodb-kubernetes-operator crashes
6. Updated members to "2" but it still crashes

**What happened instead?**
```
Running ./manager
2021-09-20T08:02:11.141Z	INFO	manager/main.go:74	Watching namespace: test-2
I0920 08:02:12.192809       7 request.go:668] Waited for 1.036238129s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/apis/vpcresources.k8s.aws/v1beta1?timeout=32s
2021-09-20T08:02:12.447Z	INFO	manager/main.go:91	Registering Components.
2021-09-20T08:02:12.447Z	INFO	manager/main.go:104	Starting the Cmd.
2021-09-20T08:02:12.549Z	INFO	controllers/replica_set_controller.go:132	Reconciling MongoDB	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.549Z	DEBUG	controllers/replica_set_controller.go:134	Validating MongoDB.Spec	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.550Z	DEBUG	controllers/replica_set_controller.go:143	Ensuring the service exists	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.563Z	INFO	controllers/replica_set_controller.go:389	The service already exists... moving forward: services "mongodb-cluster-svc" already exists	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.563Z	INFO	controllers/mongodb_tls.go:39	Ensuring TLS is correctly configured	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.664Z	INFO	controllers/mongodb_tls.go:82	Successfully validated TLS config	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.664Z	INFO	controllers/replica_set_controller.go:276	TLS is enabled, creating/updating TLS secret	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.770Z	DEBUG	controllers/replica_set_controller.go:347	Enabling TLS on an existing deployment, the StatefulSet must be updated first	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.770Z	INFO	controllers/replica_set_controller.go:287	Creating/Updating StatefulSet	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.781Z	DEBUG	controllers/replica_set_controller.go:297	Ensuring StatefulSet is ready, with type: RollingUpdate	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.781Z	INFO	controllers/replica_set_controller.go:307	Creating/Updating AutomationConfig	{"ReplicaSet": "test-2/mongodb-cluster"}
2021-09-20T08:02:12.802Z	DEBUG	scram/scram.go:165	Credentials have not changed, using credentials stored in: secret/mongodb-cluster-scram-credentials
2021-09-20T08:02:12.802Z	DEBUG	controllers/replica_set_controller.go:428	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 2}
panic: runtime error: index out of range [1] with length 1

goroutine 258 [running]:
github.com/mongodb/mongodb-kubernetes-operator/pkg/automationconfig.(*Builder).Build(0xc000749720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/pkg/automationconfig/automation_config_builder.go:239 +0x15ff
github.com/mongodb/mongodb-kubernetes-operator/controllers.buildAutomationConfig(0x1578f33, 0x10, 0xc0007924a0, 0x1f, 0xc0006e9470, 0xf, 0x0, 0x0, 0xc0006e9480, 0x6, ...)
	/workspace/controllers/replica_set_controller.go:444 +0x84c
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.buildAutomationConfig(0x1b19270, 0xc0003136b0, 0xc000250460, 0xc00000e108, 0xc0004626e8, 0x1578f33, 0x10, 0xc0007924a0, 0x1f, 0xc0006e9470, ...)
	/workspace/controllers/replica_set_controller.go:519 +0x7e5
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.ensureAutomationConfig(0x1b19270, 0xc0003136b0, 0xc000250460, 0xc00000e108, 0xc0004626e8, 0x1578f33, 0x10, 0xc0007924a0, 0x1f, 0xc0006e9470, ...)
	/workspace/controllers/replica_set_controller.go:412 +0xf3
github.com/mongodb/mongodb-kubernetes-operator/controllers.(*ReplicaSetReconciler).deployAutomationConfig(0xc000755d10, 0x1578f33, 0x10, 0xc0007924a0, 0x1f, 0xc0006e9470, 0xf, 0x0, 0x0, 0xc0006e9480, ...)
	/workspace/controllers/replica_set_controller.go:314 +0x2f6
github.com/mongodb/mongodb-kubernetes-operator/controllers.(*ReplicaSetReconciler).deployMongoDBReplicaSet.func1(0x1, 0x0, 0x0)
	/workspace/controllers/replica_set_controller.go:378 +0x68
github.com/mongodb/mongodb-kubernetes-operator/pkg/util/functions.runReversed(0xc0007508e0, 0x2, 0x2, 0x4e, 0xc000044ed6, 0xc000044ea0)
	/workspace/pkg/util/functions/functions.go:29 +0x4c
github.com/mongodb/mongodb-kubernetes-operator/pkg/util/functions.RunSequentially(0xc000755d00, 0xc0007508e0, 0x2, 0x2, 0x1f, 0xc0006e9470, 0xf)
	/workspace/pkg/util/functions/functions.go:11 +0x95
github.com/mongodb/mongodb-kubernetes-operator/controllers.(*ReplicaSetReconciler).deployMongoDBReplicaSet(0xc000755d10, 0x1578f33, 0x10, 0xc0007924a0, 0x1f, 0xc0006e9470, 0xf, 0x0, 0x0, 0xc0006e9480, ...)
	/workspace/controllers/replica_set_controller.go:376 +0x128
github.com/mongodb/mongodb-kubernetes-operator/controllers.ReplicaSetReconciler.Reconcile(0x1b19270, 0xc0003136b0, 0xc000250460, 0xc00000e108, 0xc0004626e8, 0x1afc858, 0xc0001cdfb0, 0xc0006e9480, 0x6, 0xc0006e9470, ...)
	/workspace/controllers/replica_set_controller.go:185 +0x11ea
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005bc0a0, 0x1afc7b0, 0xc000362040, 0x16e91e0, 0xc00046a000)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005bc0a0, 0x1afc7b0, 0xc000362040, 0x0)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000545bb0, 0xc0005bc0a0, 0x1afc7b0, 0xc000362040)
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:210 +0x425
```

My MongoDBCommunity yaml:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-cluster
  namespace: test-2
spec:
  type: ReplicaSet
  version: "4.2.16"
  members: 2
  replicaSetHorizons:
    - horizon: mongodb.test-2.example.com:27017
  security:
    tls:
      enabled: true
      optional: true
      certificateKeySecretRef:
        name: common-tls
      caConfigMapRef:
        name: common-tls-ca
    authentication:
      modes: ["SCRAM", "SCRAM-SHA-1", "SCRAM-SHA-256"]
  users:
  - name: root
    db: admin
    passwordSecretRef:
      name: mongodb-cluster-admin
    roles:
    - name: root
      db: admin
    scramCredentialsSecretName: mongodb-cluster
  additionalMongodConfig:
    net.tls.allowInvalidHostnames: true
    security.javascriptEnabled: false
    storage.directoryPerDB: true
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    storage.wiredTiger.engineConfig.directoryForIndexes: true

  statefulSet:
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: mongodb-cluster
      template:
        metadata:
          labels:
            app.kubernetes.io/name: mongodb-cluster
        spec:
          containers:
          - name: mongod
            resources:
              requests:
                cpu: 500m
                memory: 1024M
              limits:
                cpu: 1000m
                memory: 1024M
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mongodb-cluster
                topologyKey: topology.kubernetes.io/zone
          dnsConfig:
            options:
            - name: ndots
              value: "1"
          nodeSelector:
            dedicated: test-spot
          tolerations:
          - key: dedicated
            value: test-spot

```

**Comment by olfway** [comment]
Tried to decrease members to "1" - this fixes operator
But after increase to "3" it starts crashing again

**Comment by olfway** [comment]
It seems that's because of replicaSetHorizons misconfiguration

**Comment by priyolahiri** [comment]
You need to have a corresponding number of horizon entries for the value you have set in members. For example if:

`members: 2`

then

```
replicaSetHorizons:
    - horizon: mongodb.test-2.example.com:27017
    - horizon: mongodb.test-3.example.com:27018
```

**Comment by priyolahiri** [comment]
Refer to: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/config/samples/external_access/mongodb.com_v1_mongodbcommunity_cr.yaml

**Comment by priyolahiri** [comment]
Please feel free to re-open if your issue is not resolved after the correct configuration.
