### ISSUE TITLE
MongoDBCommunity Resource stuck in Pending (Readiness probe failed: fatal)

### ISSUE THREAD

**Issue by steckel** [mongodb/mongodb-kubernetes-operator#921]
**What did you do to encounter the bug?**

(using Kind for a K8 cluster `kind create cluster --name example`)

```
git clone https://github.com/mongodb/mongodb-kubernetes-operator.git
cd mongodb-kubernetes-operator
git checkout v0.7.3
```

edit `config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml` so that password is "password"

```diff
 ---
 apiVersion: mongodbcommunity.mongodb.com/v1
 kind: MongoDBCommunity
 metadata:
   name: example-mongodb
 spec:
   members: 3
   type: ReplicaSet
   version: "4.2.6"
   security:
     authentication:
       modes: ["SCRAM"]
   users:
     - name: my-user
       db: admin
       passwordSecretRef: # a reference to the secret that will be used to generate the user's password
         name: my-user-password
       roles:
         - name: clusterAdmin
           db: admin
         - name: userAdminAnyDatabase
           db: admin
       scramCredentialsSecretName: my-scram
   statefulSet:
     spec:
       selector:
         matchLabels:
           app: mongodb
       template:
         metadata:
           # label the pod which is used by the "labelSelector" in podAntiAffinty
           # you can label it witch some other labels as well -- make sure it change the podAntiAffinity labelselector accordingly
           labels:
             app: mongodb
         spec:
           affinity:
             podAntiAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
                 - weight: 100
                   podAffinityTerm:
                     labelSelector:
                       matchExpressions:
                         - key: app
                           operator: In
                           values:
                             - mongodb
                     topologyKey: kubernetes.io/hostname
 
 # the user credentials will be generated from this secret
 # once the credentials are generated, this secret is no longer required
 ---
 apiVersion: v1
 kind: Secret
 metadata:
   name: my-user-password
 type: Opaque
 stringData:
-   password: <your-password-here>
+   password: password
```

```
kubectl create namespace example
kubectl config set-context --current --namespace=example
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
kubectl apply -k config/rbac/
kubectl create -f config/manager/manager.yaml
kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_cr.yaml
```

wait some time then `kubectl get pods` and `kubectl get mongodbcommunity`

```
NAME                                           READY   STATUS    RESTARTS   AGE
example-mongodb-0                              1/2     Running   0          24s
mongodb-kubernetes-operator-5d99d7755f-sht4r   1/1     Running   0          29s
```

```
NAME              PHASE     VERSION
example-mongodb   Pending
```

When looking at the mongodb-agent logs (via `kubectl logs example-mongodb-0 -c mongodb-agent`) I find `['currentState.Fickle.AllRsMembersUp() ' = false]`.

```
[2022-03-12T14:00:36.406+0000] [.info] [src/config/config.go:ReadClusterConfig:437] [14:00:36.406] Retrieving cluster config from /var/lib/automation/config/cluster-config.json...
[2022-03-12T14:00:36.406+0000] [.info] [main/components/agent.go:LoadClusterConfig:270] [14:00:36.406] clusterConfig unchanged
[2022-03-12T14:00:36.803+0000] [.info] [src/mongoclientservice/mongoclientservice.go:func1:1573] [14:00:36.803] Testing auth with username __system db=local to example-mongodb-0.example-mongodb-svc.example.svc.cluster.local:27017 (local=false) connectMode=SingleConnect ipversion=0 tls=false
[2022-03-12T14:00:36.908+0000] [.info] [src/mongoctl/processctl.go:GetKeyHashes:2026] <example-mongodb-0> [14:00:36.908] Able to successfully auth to example-mongodb-0.example-mongodb-svc.example.svc.cluster.local:27017 (local=false) using desired auth key
[2022-03-12T14:00:36.911+0000] [.warn] [src/mongoclientservice/mongoclientservice.go:sendClientToRequesters:698] [14:00:36.911] Client ready for connParams=example-mongodb-0.example-mongodb-svc.example.svc.cluster.local:27017 (local=false) connectMode=SingleConnect but client 0xc000147880 is no longer in our list.  Disconnecting client...
[2022-03-12T14:00:37.134+0000] [.info] [src/mongoctl/processctl.go:Update:3307] <example-mongodb-0> [14:00:37.134] <DB_WRITE> Updated with query map[] and update [{$set [{agentFeatures [StateCache]} {nextVersion 1}]}] and upsert=true on local.clustermanager
[2022-03-12T14:00:37.309+0000] [.info] [src/director/director.go:computePlan:279] <example-mongodb-0> [14:00:37.309] ... process has a plan : WaitAllRsMembersUp,RsInit,WaitFeatureCompatibilityVersionCorrect
[2022-03-12T14:00:37.309+0000] [.info] [src/director/director.go:tracef:793] <example-mongodb-0> [14:00:37.309] Running step: 'WaitAllRsMembersUp' of move 'WaitAllRsMembersUp'
[2022-03-12T14:00:37.309+0000] [.info] [src/director/director.go:tracef:793] <example-mongodb-0> [14:00:37.309] because
[All the following are true:
    ['currentState.Up' = true]
    ['desiredState.ReplSetConf' != <nil> ('desiredState.ReplSetConf' = ReplSetConfig{id=example-mongodb,version=0,commitmentStatus=false,configsvr=false,protocolVersion=1,forceProtocolVersion=false,writeConcernMajorityJournalDefault=,members={id:0,HostPort:example-mongodb-0.example-mongodb-svc.example.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:1,HostPort:example-mongodb-1.example-mongodb-svc.example.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},{id:2,HostPort:example-mongodb-2.example-mongodb-svc.example.svc.cluster.local:27017,ArbiterOnly:falsePriority:1,Hidden:false,SecondaryDelaySecs:0,Votes:1,Tags:map[]},settings=map[]})]
]
[2022-03-12T14:00:37.310+0000] [.info] [src/director/director.go:planAndExecute:563] <example-mongodb-0> [14:00:37.310] Step=WaitAllRsMembersUp as part of Move=WaitAllRsMembersUp in plan failed : <example-mongodb-0> [14:00:37.310] Postcondition not yet met for step WaitAllRsMembersUp because
['currentState.Fickle.AllRsMembersUp() ' = false].
 Recomputing a plan...
```

describing the pod (kubectl describe pod example-mongodb-0) seems to reveal a busted readiness probe?

```
Name:         example-mongodb-0
Namespace:    example
Priority:     0
Node:         example-control-plane/172.18.0.2
Start Time:   Sat, 12 Mar 2022 05:59:39 -0800
Labels:       app=example-mongodb-svc
              controller-revision-hash=example-mongodb-d649d6694
              statefulset.kubernetes.io/pod-name=example-mongodb-0
Annotations:  <none>
Status:       Running
IP:           10.244.0.8
IPs:
  IP:           10.244.0.8
Controlled By:  StatefulSet/example-mongodb
Init Containers:
  mongod-posthook:
    Container ID:  containerd://5f0f6ddc01ebf2ffaebf28e8be6b3faf64ff740954705650fda9bc95d37d62d5
    Image:         quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook@sha256:64b27b76e89279664c227c9f6a31fd7c243a40d90b06b79e840d5488b81fd806
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      version-upgrade-hook
      /hooks/version-upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 12 Mar 2022 05:59:41 -0800
      Finished:     Sat, 12 Mar 2022 05:59:41 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /hooks from hooks (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qw8gd (ro)
  mongodb-agent-readinessprobe:
    Container ID:  containerd://f6d163347368a05609faf0125e07d6ea138457fc77428c6a0361ddefdd00e16b
    Image:         quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8
    Image ID:      quay.io/mongodb/mongodb-kubernetes-readinessprobe@sha256:fccc2a2e9da0072d24fcabb896d5536e4c292cc5ead4788b7cfcaf751bb3328e
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /probes/readinessprobe
      /opt/scripts/readinessprobe
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 12 Mar 2022 05:59:44 -0800
      Finished:     Sat, 12 Mar 2022 05:59:44 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /opt/scripts from agent-scripts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qw8gd (ro)
Containers:
  mongod:
    Container ID:  containerd://4d0450393012e9f0849dab304390eecbe349454b6aac003deb99f40cd2c491f0
    Image:         docker.io/mongo:4.2.6
    Image ID:      docker.io/library/mongo@sha256:c880f6b56f443bb4d01baa759883228cd84fa8d78fa1a36001d1c0a0712b5a07
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      
      #run post-start hook to handle version changes
      /hooks/version-upgrade
      
      # wait for config and keyfile to be created by the agent
       while ! [ -f /data/automation-mongod.conf -a -f /var/lib/mongodb-mms-automation/authentication/keyfile ]; do sleep 3 ; done ; sleep 2 ;
      
      # with mongod configured to append logs, we need to provide them to stdout as
      # mongod does not write to stdout and a log file
      tail -F /var/log/mongodb-mms-automation/mongodb.log > /dev/stdout &
      
      # start mongod with this configuration
      exec mongod -f /data/automation-mongod.conf;
      
      
    State:          Running
      Started:      Sat, 12 Mar 2022 05:59:52 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:     500m
      memory:  400M
    Environment:
      AGENT_STATUS_FILEPATH:  /healthstatus/agent-health-status.json
    Mounts:
      /data from data-volume (rw)
      /healthstatus from healthstatus (rw)
      /hooks from hooks (rw)
      /var/lib/mongodb-mms-automation/authentication from example-mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qw8gd (ro)
  mongodb-agent:
    Container ID:  containerd://eb7e4cc2c89a1b455d10d0143673b5898f31dd7d0ce6038e43bc52e0f52a6c7d
    Image:         quay.io/mongodb/mongodb-agent:11.12.0.7388-1
    Image ID:      quay.io/mongodb/mongodb-agent@sha256:e79b314bc8c986d4bc5495b2175db6930c4d9b53d9807419b217fca329a561d3
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      current_uid=$(id -u)
      AGENT_API_KEY="$(cat /mongodb-automation/agent-api-key/agentApiKey)"
      declare -r current_uid
      if ! grep -q "${current_uid}" /etc/passwd ; then
      sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
      echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
      export NSS_WRAPPER_PASSWD=/tmp/passwd
      export LD_PRELOAD=libnss_wrapper.so
      export NSS_WRAPPER_GROUP=/etc/group
      fi
      agent/mongodb-agent -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -cluster=/var/lib/automation/config/cluster-config.json -skipMongoStart -noDaemonize -useLocalMongoDbTools
    State:          Running
      Started:      Sat, 12 Mar 2022 05:59:59 -0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  500M
    Requests:
      cpu:      500m
      memory:   400M
    Readiness:  exec [/opt/scripts/readinessprobe] delay=5s timeout=1s period=10s #success=1 #failure=40
    Environment:
      AGENT_STATUS_FILEPATH:  /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      AUTOMATION_CONFIG_MAP:  example-mongodb-config
      HEADLESS_AGENT:         true
      POD_NAMESPACE:          example (v1:metadata.namespace)
    Mounts:
      /data from data-volume (rw)
      /opt/scripts from agent-scripts (rw)
      /var/lib/automation/config from automation-config (ro)
      /var/lib/mongodb-mms-automation/authentication from example-mongodb-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/log/mongodb-mms-automation/healthstatus from healthstatus (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qw8gd (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-volume-example-mongodb-0
    ReadOnly:   false
  logs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  logs-volume-example-mongodb-0
    ReadOnly:   false
  agent-scripts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  automation-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  example-mongodb-config
    Optional:    false
  example-mongodb-keyfile:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  healthstatus:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hooks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-qw8gd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age    From               Message
  ----     ------     ----   ----               -------
  Normal   Scheduled  3m35s  default-scheduler  Successfully assigned example/example-mongodb-0 to example-control-plane
  Normal   Pulling    3m35s  kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4"
  Normal   Pulled     3m33s  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4" in 1.651349126s
  Normal   Created    3m33s  kubelet            Created container mongod-posthook
  Normal   Started    3m33s  kubelet            Started container mongod-posthook
  Normal   Pulling    3m32s  kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8"
  Normal   Created    3m31s  kubelet            Created container mongodb-agent-readinessprobe
  Normal   Pulled     3m31s  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.8" in 1.628927293s
  Normal   Started    3m30s  kubelet            Started container mongodb-agent-readinessprobe
  Normal   Pulling    3m30s  kubelet            Pulling image "docker.io/mongo:4.2.6"
  Normal   Pulled     3m22s  kubelet            Successfully pulled image "docker.io/mongo:4.2.6" in 8.273759295s
  Normal   Created    3m22s  kubelet            Created container mongod
  Normal   Pulling    3m22s  kubelet            Pulling image "quay.io/mongodb/mongodb-agent:11.12.0.7388-1"
  Normal   Started    3m22s  kubelet            Started container mongod
  Normal   Pulled     3m15s  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-agent:11.12.0.7388-1" in 7.123303628s
  Normal   Created    3m15s  kubelet            Created container mongodb-agent
  Normal   Started    3m15s  kubelet            Started container mongodb-agent
  Warning  Unhealthy  3m5s   kubelet            Readiness probe failed: fatal: morestack on g0
SIGTRAP: trace trap
PC=0x80a7582 m=1 sigcode=128

goroutine 0 [idle]:
runtime.abort()
  /usr/local/go/src/runtime/asm_386.s:847 +0x2
runtime.morestack()
  /usr/local/go/src/runtime/asm_386.s:422 +0x24

goroutine 1 [running, locked to thread]:
  goroutine running on other thread; stack unavailable

eax    0x17
ebx    0x2
ecx    0x9053004
edx    0x17
edi    0x9757770
esi    0x9c003c0
ebp    0x807bd60
esp    0x9c50668
eip    0x80a7582
eflags 0x202
cs     0x23
fs     0x0
gs     0x33
  Warning  Unhealthy  2m55s  kubelet  Readiness probe failed: fatal: bad g in signal handler
  Warning  Unhealthy  2m35s  kubelet  Readiness probe failed: fatal: morestack on g0
SIGTRAP: trace trap
PC=0x80a7582 m=1 sigcode=128

goroutine 0 [idle]:
runtime.abort()
  /usr/local/go/src/runtime/asm_386.s:847 +0x2
runtime.morestack()
  /usr/local/go/src/runtime/asm_386.s:422 +0x24

goroutine 1 [running, locked to thread]:
  goroutine running on other thread; stack unavailable

eax    0x17
ebx    0x2
ecx    0x9053004
edx    0x17
edi    0x8085770
esi    0x9c003c0
ebp    0x0
esp    0x9c5064c
eip    0x80a7582
eflags 0x202
cs     0x23
fs     0x0
gs     0x33
  Warning  Unhealthy  2m25s (x2 over 2m45s)  kubelet  Readiness probe failed: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x720 pc=0x808988f]

runtime stack:
runtime.throw({0x9068cb5, 0x2a})
  /usr/local/go/src/runtime/panic.go:1198 +0x6a
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:719 +0x233
runtime.runqput(0x0, 0x9c004b0, 0x1)
  /usr/local/go/src/runtime/proc.go:5960 +0xaf
runtime.newproc.func1()
  /usr/local/go/src/runtime/proc.go:4258 +0x66
runtime.systemstack()
  /usr/local/go/src/runtime/asm_386.s:376 +0x41

goroutine 1 [running, locked to thread]:
           goroutine running on other thread; stack unavailable
  Warning  Unhealthy  2m15s  kubelet  Readiness probe failed: fatal: morestack on g0
SIGTRAP: trace trap
PC=0x80a7582 m=1 sigcode=128

goroutine 0 [idle]:
runtime.abort()
  /usr/local/go/src/runtime/asm_386.s:847 +0x2
runtime.morestack()
  /usr/local/go/src/runtime/asm_386.s:422 +0x24

goroutine 1 [running, locked to thread]:
  goroutine running on other thread; stack unavailable

eax    0x17
ebx    0x2
ecx    0x9053004
edx    0x17
edi    0x950894f
esi    0x9c003c0
ebp    0x97bc3dc
esp    0x9c50630
eip    0x80a7582
eflags 0x206
cs     0x23
fs     0x0
gs     0x33
  Warning  Unhealthy  2m5s  kubelet  Readiness probe failed: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8083f30]

runtime stack:
runtime.throw({0x9068cb5, 0x2a})
  /usr/local/go/src/runtime/panic.go:1198 +0x6a
runtime.sigpanic()
  /usr/local/go/src/runtime/signal_unix.go:719 +0x233
runtime.dropg(...)
  /usr/local/go/src/runtime/proc.go:3419
runtime.goschedImpl(0x9c001e0)
  /usr/local/go/src/runtime/proc.go:3526 +0x70
runtime.gopreempt_m(0x9c001e0)
  /usr/local/go/src/runtime/proc.go:3559 +0x6f
runtime.newstack()
  /usr/local/go/src/runtime/stack.go:1055 +0x3a0
runtime.morestack()
  /usr/local/go/src/runtime/asm_386.s:455 +0x7c

goroutine 1 [runnable, locked to thread]:
runtime.step({0x9508949, 0x24dba7, 0x24dba7}, 0x9c50668, 0x9c50664, 0x0)
  /usr/local/go/src/runtime/symtab.go:1027 +0x188
runtime.funcMaxSPDelta({0x97bc3dc, 0x9a8f420})
  /usr/local/go/src/runtime/symtab.go:973 +0x97
runtime.init.5()
  /usr/local/go/src/runtime/preempt.go:319 +0x43
runtime.doInit(0x9a87340)
  /usr/local/go/src/runtime/proc.go:6498 +0xf6
runtime.main()
  /usr/local/go/src/runtime/proc.go:204 +0x14d
runtime.goexit()
           /usr/local/go/src/runtime/asm_386.s:1319 +0x1
  Warning  Unhealthy  2m  kubelet  Readiness probe failed: fatal: morestack on g0
SIGTRAP: trace trap
PC=0x80a7582 m=1 sigcode=128

goroutine 0 [idle]:
runtime.abort()
  /usr/local/go/src/runtime/asm_386.s:847 +0x2
runtime.morestack()
  /usr/local/go/src/runtime/asm_386.s:422 +0x24

goroutine 1 [running, locked to thread]:
  goroutine running on other thread; stack unavailable

eax    0x17
ebx    0x2
ecx    0x9053004
edx    0x17
edi    0x9758a80
esi    0x9c003c0
ebp    0x80a82b0
esp    0x9c50668
eip    0x80a7582
eflags 0x202
cs     0x23
fs     0x0
gs     0x33
  Warning  Unhealthy  115s  kubelet  Readiness probe failed: fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
fatal error: runtime·unlock: lock count
panic during panic

runtime stack:
runtime.throw({0x905717f, 0x1b})
  /usr/local/go/src/runtime/panic.go:1198 +0x6a
runtime.unlock2(0x9b037d4)
  /usr/local/go/src/runtime/lock_futex.go:127 +0x9e
runtime.unlockWithRank(...)
  /usr/local/go/src/runtime/lockrank_off.go:32
runtime.unlock(...)
  /usr/local/go/src/runtime/lock_futex.go:112
runtime.printunlock()
  /usr/local/go/src/runtime/print.go:80 +0x4a
runtime.throw.func1()
  /usr/local/go/src/runtime/panic.go:1192 +0x5c
runtime.throw({0x905717f, 0x1b})
  /usr/local/go/src/runtime/panic.go:1191 +0x41
runtime.unlock2(0x9b037d4)
  /usr/local/go/src/runtime/lock_futex.go:127 +0x9e
runtime.unlockWithRank(...)
  /usr/local/go/src/runtime/lockrank_off.go:32
runtime.unlock(...)
  /usr/local/go/src/runtime/lock_futex.go:112
runtime.printunlock()
  /usr/local/go/src/runtime/print.go:80 +0x4a
runtime.throw.func1()
  /usr/local/go/src/runtime/panic.go:1192 +0x5c
runtime.throw({0x905717f, 0x1b})
  /usr/local/go/src/runtime/panic.go:1191 +0x41
runtime.unlock2(0x9b037d4)
  /usr/local/go/src/runtime/lock_futex.go:127 +0x9e
runtime.unlockWithRank(...)
  /usr/local/go/src/runtime/lockrank_off.go:32
runtime.unlock(...)
  /usr/local/go/src/runtime/lock_futex.go:112
runtime.printunlock()
  /usr/local/go/src/runtime/print.go:80 +0x4a
runtime.throw.func1()
  /usr/local/go/src/runtime/panic.go:1192 +0x5c
runtime.throw({0x905717f, 0x1b})
  /usr/local/go/src/runtime/panic.go:1191 +0x41
runtime.unlock2(0x9b037d4)
  /usr/local/go/src/runtime/lock_futex.go:127 +0x9e
runtime.unlockWithRank(...)
  /usr/local/go/src/runtime/lockrank_off.go:32
runtime.unlock(...)
  /usr/local/go/src/runtime/lock_futex.go:112
```

**What did you expect?**
I would have imagined that following the instructions the straightforward way I had would result in a healthy set of resourced with readiness probes that pass, completing the deploy and creating an available and useful monogodb replicaset for use.

**What happened instead?**
The deployment is not successful, available and useful.

**Comment by remiphilippe** [comment]
same issue here, on a Mac (M1) with Docker Desktop

**Comment by remiphilippe** [comment]
for the record, I ended up rebuilding the readiness probe container with multi arch and removed the forced GOARCH here:
https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/scripts/dev/templates/readiness/Dockerfile.builder

Works fine like that, images are here https://hub.docker.com/repository/docker/remiphilippe/mongodb-kubernetes-readinessprobe

I noticed that the agent is also build for amd64 only, for now seems ok

**Comment by steckel** [comment]
Good find @remiphilippe. I'm also on an M1 Mac and completely forgot (switching between work and personal computers frequently). I'll try this soon. I imagine this isn't simple to contribute back up as it would require CI changes more than code huh?

**Comment by remiphilippe** [comment]
Unfortunately it's not enough :) mongo-agent is amd64 too and flaky with qemu. There are binaries here https://github.com/mongodb/mongodb-kubernetes-operator/issues/792 but i couldn't get it to work correctly (I have an image here https://hub.docker.com/r/remiphilippe/mongodb-agent but didn't have time to troubleshoot it properly). It seems agent is still looking for an amd64 image when you start the db, but we don't have the code to this afaik.

It's indeed a ci thing with docker buildx

**Comment by SaurabhSK123** [comment]
I also find the same issue can anyone solve this issue.

can't open new logfile: open /var/log/mongodb-mms-automation/readiness.log: permission denied

**Comment by lsierant** [comment]
Is is indeed problem with readiness-probe's arch on M1 macs.
#976 should fix the issue.

**Comment by irajdeep** [comment]
I am closing this issue, as mentioned by @lsierant this should be fixed in the next operator release: https://github.com/mongodb/mongodb-kubernetes-operator/pull/976
