### ISSUE TITLE
config/acVersion/version: no such file or directory

### ISSUE THREAD

**Issue by jicki** [mongodb/mongodb-kubernetes-operator#972]
**Operator Information**
 - Operator Version:  0.7.3
 - MongoDB Image used:  4.4.13
 - mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.4"
 - mongodb-agent:11.12.0.7388-1
 - mongodb-kubernetes-readinessprobe:1.0.8"

**Kubernetes Cluster Information**
 - Distribution
 - Version: v1.17.9

If possible, please include:

* describe pods demo-mongodb-0

```bash

  Normal   Created                 4m17s                 kubelet                  Created container mongodb-agent
  Normal   Started                 4m17s                 kubelet                  Started container mongodb-agent
  Warning  Unhealthy               2m53s (x8 over 4m3s)  kubelet                  Readiness probe failed: panic: open /var/lib/automation/config/acVersion/version: no such file or directory

goroutine 1 [running]:
main.main()
  /build/main.go:225 +0x14b
```

* logs mongo-operator 

```bash
2022-05-12T01:43:38.231Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds
2022-05-12T01:43:48.238Z	INFO	controllers/replica_set_controller.go:140	Reconciling MongoDB	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.238Z	DEBUG	controllers/replica_set_controller.go:142	Validating MongoDB.Spec	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.238Z	DEBUG	controllers/replica_set_controller.go:151	Ensuring the service exists	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.245Z	INFO	controllers/replica_set_controller.go:475	Create/Update operation succeeded	{"ReplicaSet": "mongo-replicaset/demo-mongodb", "operation": "updated"}
2022-05-12T01:43:48.245Z	DEBUG	controllers/replica_set_controller.go:160	Ensuring the service for Arbiters exists	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.251Z	INFO	controllers/replica_set_controller.go:475	Create/Update operation succeeded	{"ReplicaSet": "mongo-replicaset/demo-mongodb", "operation": "updated"}
2022-05-12T01:43:48.251Z	INFO	controllers/replica_set_controller.go:371	Creating/Updating AutomationConfig	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.270Z	DEBUG	scram/scram.go:166	Credentials have not changed, using credentials stored in: secret/my-scram-scram-credentials
2022-05-12T01:43:48.271Z	DEBUG	controllers/replica_set_controller.go:525	AutomationConfigMembersThisReconciliation	{"mdb.AutomationConfigMembersThisReconciliation()": 3}
2022-05-12T01:43:48.271Z	DEBUG	controllers/replica_set_controller.go:394	Waiting for agents to reach version 1	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.271Z	DEBUG	agent/agent_readiness.go:61	The Pod 'demo-mongodb-0' doesn't have annotation 'agent.mongodb.com/version' yet	{"ReplicaSet": "mongo-replicaset/demo-mongodb"}
2022-05-12T01:43:48.271Z	INFO	controllers/mongodb_status_options.go:110	ReplicaSet is not yet ready, retrying in 10 seconds

```

**Comment by Brice187** [comment]
Duplicate: https://github.com/mongodb/mongodb-kubernetes-operator/issues/949

**Comment by priyolahiri** [comment]
We are currently looking into this issue and hope to have a resolution soon.

**Comment by jicki** [comment]
> Hi @jicki
> 
> Could you please check if a secret named `demo-mongodb-config` is present in the namespace?

I think I found the problem, configmap is needed in rc
